# master .travis.yml 20151223 16:30
# whitelist
branches:
  only:
    - master
    - testing
 
language: c

rvm:
    - 2.0.0
addons:
  apt:
    packages:
    - cmake
    - xsltproc

sudo: false

#install:
#    - bundle install --gemfile=test/benchmarks/Gemfile

before_script:
    - cd build/cmake
    - cmake ../..
    - make
    - cd ../../test/
    - ls -l ../build/cmake/tidy
    - ls -l ../build/cmake/
script:
    - ./testall.sh
    - diff -ua testbase tmp

# eof
