# master .travis.yml 20151223 16:30
# whitelist
branches:
  only:
    - master
 
language: c

rvm:
    - 2.0.0
addons:
  apt:
    packages:
    - cmake
    - xsltproc

sudo: false

#install:
#    - bundle install --gemfile=test/benchmarks/Gemfile

script:
    - cd build/cmake
    - cmake ../..
    - make

# eof
